### ISSUE TITLE
In win11: System Error -> libdl.dll was not found

### ISSUE THREAD

**Issue by no-e-in** [trealla-prolog/trealla#290] opened 2023-08-03 10:00 UTC

**Comment by infradig** [comment] 2023-08-04 01:53
Maybe @guregu has an idea.

**Comment by guregu** [comment] 2023-08-05 21:28
I only have a Windows 10 machine to work with but I'll see if I can reproduce 🙏

**Comment by guregu** [comment] 2023-08-05 22:08
Submitted a fix at #294, the next release after that's merged should have a working Windows release.

**Comment by infradig** [comment] 2023-08-06 00:08
Hopefully fixed for you now.

**Comment by pmoura** [comment] 2023-08-06 06:09
Btw, the Logtalk installer for Windows provide preliminary support for Trealla Prolog. But it's currently non-functional, most likely due to path representation issues on Windows. If those issues are solved, all the Logtalk distribution tests could be run.

**Comment by infradig** [comment] 2023-08-06 09:46
Thanks, worth look into. I remember you once saying not to do anything
special for DOS/Windows paths, I may need to follow through on that.

**Comment by no-e-in** [comment] 2023-08-08 12:47
ok

**Closed as completed** 2023-08-08 12:47 UTC
